[manager]
fg = "#c0caf5"
bg = "#000000"

[manager.current]
fg = "#c0caf5"
bg = "#000000"

[manager.current.hovered]
fg = "#c0caf5"
bg = "#1d1d2b"

[manager.current.selected]
fg = "#7aa2f7"
bg = "#1d1d2b"

[manager.preview_hovered]
fg = "#c0caf5"
bg = "#000000"

[manager.preview_hovered.selected]
fg = "#7aa2f7"
bg = "#1d1d2b"

[manager.preview]
fg = "#a9b1d6"
bg = "#000000"

[manager.preview.selected]
fg = "#7aa2f7"
bg = "#1d1d2b"

[manager.border]
fg = "#414868"
bg = "#000000"

[manager.border_style]
fg = "#414868"

[status]
fg = "#a9b1d6"
bg = "#1d1d2b"

[status.separator_style]
fg = "#414868"
bg = "#1d1d2b"

[status.selected]
fg = "#7aa2f7"
bg = "#1d1d2b"

[status.progress]
fg = "#7aa2f7"
bg = "#33467c"

[status.progress_inactive]
fg = "#a9b1d6"
bg = "#1d1d2b"

[input]
fg = "#c0caf5"
bg = "#000000"

[input.border]
fg = "#7aa2f7"

[select]
fg = "#c0caf5"
bg = "#000000"

[select.border]
fg = "#bb9af7"

[tab]
fg = "#414868"
bg = "#000000"

[tab.active]
fg = "#c0caf5"
bg = "#000000"

[tab.inactive]
fg = "#414868"
bg = "#000000"

[tab.width]
min = 1
max = 30

[which]
fg = "#c0caf5"
bg = "#1d1d2b"

[which.border]
fg = "#bb9af7"

[help]
fg = "#a9b1d6"
bg = "#000000"

[help.border]
fg = "#414868"

[help.header]
fg = "#7aa2f7"
bg = "#000000"

[help.footer]
fg = "#a9b1d6"
bg = "#1d1d2b"

[help.on]
fg = "#9ece6a"

[help.run]
fg = "#e0af68"

[help.desc]
fg = "#a9b1d6"

[notify]
bg = "#000000"

[notify.info]
fg = "#7aa2f7"
bg = "#1d1d2b"

[notify.warning]
fg = "#e0af68"
bg = "#1d1d2b"

[notify.error]
fg = "#f7768e"
bg = "#1d1d2b"

[tasks]
fg = "#a9b1d6"
bg = "#000000"

[tasks.border]
fg = "#7aa2f7"

[mode]
fg = "#000000"
bg = "#7aa2f7"
